#=================================================#
#                                                 #
#             HyPractice Configuration            #
#                                                 #
#=================================================#
LICENSE: ''

# Use HyPractice tablist
TABLIST_ENABLE: true
MESSAGE-REPLY-BOOLEAN: true
ESSENTIAL_SPAWN_LOCATION: world:-9999.617585349535:100.63557196779635:245.40600562996698:180.02081:5.390071
MOD_MODE: true

# Default language. Currently Supported: English , Espaniol
DEFAULT_LANG: EN

# You can use 'MONGO' or 'MONGODB' and 'FLATFILE' or 'FILE'
# If you use the MONGO method you can get information
# from there for external things like web pages or other statistical things
SAVE_METHOD: MONGO

# Command to execute on purchase of cosmetic
PURCHASE-COSMETICS-CMD: pex user {player} setpermission cosmetics.killeffects.{effect}

# Chat formats for GLOBAL & CLAN CHAT
CHAT:
  # Global chat format
  DEFAULT_FORMAT: '{prefix} {player}&7:&r {message}'
  # Clan chat format
  CLAN_FORMAT: '&7[{clan}&7] &r{prefix}{player}&7:&r {message}'
# Match configuration
MATCH:
  # How many rounds should a bridge match last
  ROUNDS_BRIDGE: 3
  # How many rounds should a ranked sumo match last
  ROUNDS_RANKED_SUMO: 1
  # Remove blocks each bridge round
  REMOVE_BLOCKS_ON_ROUND_END_BRIDGE: false
  # Remove empty potion bottles
  REMOVE_POTION_BOTTLE_ON_CONSUME: false
  # Drop items in inventory on player death
  DROP_ITEMS_ON_DEATH: false
  # Fast pot
  FAST_POTION: false
  # How many hits needed to win a boxing match
  BOXING_MAX_HITS: 100

# FFA configuration
FFA:
  # Default FFA Kit
  KIT: NoDebuff
  # FFA Safezone Coords
  SAFEZONE:
    location1: world:124.0:96.0:-1078.0:0.0:0.0
    location2: world:126.0:96.0:-1076.0:0.0:0.0

# Queue configuration
QUEUE:
  AMOUNT_PER_FIGHTS: true
  # Unranked Queue settings
  UNRANKED:
    # GUI Title
    INVENTORY_TITLE: '&bSelect a Kit (Unranked)'
    # kit item color
    NAME_COLOR: AQUA
    # kit item lore
    LORE:
    - '{bars}'
    - '&bIn Fighting&7: &7{in-fight}'
    - '&bIn Queueing&7: &7{in-queue}'
    - ''
    - '&7You have a &b{winstreak} &7winstreak.'
    - '{bars}'
  # Ranked Queue settings
  RANKED:
    # GUI Title
    INVENTORY_TITLE: '&bSelect a Kit (Ranked)'
    # kit item color
    NAME_COLOR: AQUA
    # kit item lore
    LORE:
    - '{bars}'
    - '&bIn Fighting&7: &r{in-fight}'
    - '&bIn Queueing&7: &r{in-queue}'
    - ''
    - '&7Your elo is &b{elo}'
    - '{bars}'

# Party configuration
PARTY:
  # Default host party size limit
  DEFAULT_LIMIT: 50
  # Vip host party size limit
  VIP_LIMIT: 100

# Name-tag configuration
NAMETAGS:
  # default player color
  DEFAULT_COLOR: '%color%'
  # party member color?
  PARTY_COLOR: AQUA
  # event participants color?
  EVENT_COLOR: AQUA
  # Clan prefix
  CLAN_FORMAT: '&7[%color%%clan%&7] &r'
  # Staff prefix
  STAFF_FORMAT: '&b[Staff] %color%'


# Points needed to win a clan tournament?
WINNING-POINTS-CLAN-TOURNAMENT: 10